version: '2'
services:
  mongo-db:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "db_data:/var/lib/mongodb/data"
    networks:
      - app_network

  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    networks:
      - app_network   
    depends_on:
      - mongo-db
    links:
      - mongo-db
volumes:
  db_data:
  gem_cache:

networks:
  app_network:
